### ISSUE TITLE
Consider wuffs

### ISSUE THREAD

**Issue by zellyn** [mvdan/zstd#2]
Very excited to see this project: it would be lovely to have a solid native Go implementation.

One thought: consider using [wuffs](https://github.com/google/wuffs) for this project. It would probably be harder, but

* it's the right way to do this kind of thing (or _one of_ the really good right ways)
* it would be epic, because you'd end up with C and Rust implementations too
* you'd basically become a ninja if you could pull it off
* @nigeltao would be great to collaborate with if he's able

Just a thought :-)

**Comment by mvdan** [comment]
This is an interesting idea, thanks for the thought. I was thinking of keeping this decompressor a toy project since Klaus is already working on a Go implementation. But a decompressor written in wuffs could have its own edge.

**Comment by mvdan** [comment]
I see that wuffs doesn't generate Go code just yet, though. So an implementation in wuffs would remain a toy project until wuffs hits 1.0.

Otherwise, this seems like a good way forward - I'll see how hard it is to move the existing code to wuffs.

**Comment by mvdan** [comment]
I'll do this; thanks for the suggestion. It might take me a while to get something trivial working, though.
