### ISSUE TITLE
Wuffs style notes

### ISSUE THREAD

**Issue by nigeltao** [mvdan/zstd#3]
Just a few drive-by comments on Wuffs style, in no particular order:

- `wuffmain.c` looks like it's based from `example/gifplayer/gifplayer.c` in the Wuffs repo. That example first reads all of stdin into memory, since playing an animated GIF requires re-winding the input back to the start. For a zstd decoder, you might want to rebase off of `example/zcat/zcat.c` instead. That latter example is very recent. You might not have seen it when you first looked.

- Speaking of `wuffmain.c`, it should probably be `wuffsmain.c`.

- Wuffs names are `snake_case`, not `camelCase`. Yeah, Wuffs differs from Go here.

---

BTW, thanks for trying Wuffs!

Be warned, though, that the language is very unstable, and I'll undoubtedly be making breaking changes for the forseeable future. Also, I don't know what your timeline is, and having Wuffs generate Go code is certainly a goal of mine, but it's not a short term goal of mine. As I said, the Wuffs language is unstable, and it'd be harder to change the Wuffs language the more target languages we're code-generating for.

Having said all that, I'll repeat that it's great that you're trying Wuffs. I just wanted to make sure you knew what you're building on.

**Comment by mvdan** [comment]
> That latter example is very recent. You might not have seen it when you first looked.

Yes, I knew that my existing main file wasn't ideal - just wanted something that would work ok enough with the simple test cases that I had so far. I imagined I'd have more issues with the Wuffs language and tools before I'd have issues with fixed length buffers :) Thanks for the pointer though, will definitely replace it.

> it should probably be wuffsmain.c

Can't remember why I named it that, probably just a typo. Thanks.

> Wuffs names are snake_case, not camelCase. Yeah, Wuffs differs from Go here.

Ah - I still prefer camel case, but I'll accept that consistency is preferrable :)

> I just wanted to make sure you knew what you're building on.

Yes, of course. Note that there is already a zstd package that wraps the original software with cgo, and Klaus is working on a pure Go implementation that will be ready as a decoder much, much earlier than mine. So I'm not concerned with stability or how fast I get to 1.0, at least not for now. I treat this as a fun experiment above all.

That answers your concerns about Wuffs the language and tools being unstable, and Go not coming soon - it's fine if neither is in the roadmap for the next year. I just hope it's in the roadmap at some point :) However, I'll do my best to report issues and make suggestions where I see fit. And, if you'd like me to help coding any part of it (or even just reviewing), please do let me know.

Unless you say there are parts that you'd like help with, I'll stay away from contributions, unless there are simple fixes that I come up with. You seem to have a vision for the project, and I don't understand quite a lot of the code, so me trying to advance it by throwing code at you is likely not going to be very useful.
