### ISSUE TITLE
Figure out how to fix wuffs_zstd__status__string compilation error

### ISSUE THREAD

**Issue by mvdan** [mvdan/zstd#4]
The code in question is extremely similar to `example/zcat/zcat.c` as of master:

```
if (s != WUFFS_BASE__SUSPENSION_SHORT_WRITE) {
        return wuffs_zstd__status__string(s);
}
```

```
$ ./build
/tmp/cca08HNl.o:wuffsmain.c:function wuffs_zstd__status__string: error: undefined reference to 'wuffs_base__status__string'
collect2: error: ld returned 1 exit status
```

@nigeltao any ideas? It seems like the generated C code is missing the `wuffs_base__status__string` implementation. Not sure if that's expected, or if I am missing anything special.

**Comment by nigeltao** [comment]
Yeah, a recent change (https://github.com/google/wuffs/commit/43bb14e88612c217911af353e780595b40bed828) means that, somewhere, you'll need to add:

```
#include "$WUFFSROOT/gen/c/base.c"
```

The original intention was to generate a stand-alone .c file, but given that error strings (and C functions) should be declared exactly once, Wuffs now requires a separate `base.c` to hold those.

If you really want to ship a stand-alone .c file, you should be able to re-stitch your separate, generated .c files back together via the recently added `wuffs-c genrelease` command.

**Comment by mvdan** [comment]
@nigeltao thanks - including the file in the build script did indeed fix the issue. I couldn't figure out how to end up with a stand-alone C file with `wuffs-c genrelease`, though, but I don't need that right now.

**Comment by mvdan** [comment]
@nigeltao I'm having issues with this again :) Please see the latest change in master.

I saw the recent changes to `examples/zcat/zcat.c`, but applying the same changes doesn't seem to fix it. `base.c` is also gone, and including `$WUFFSROOT/release/c/unsupported-snapshot.h` just results in tons of errors.

Any ideas? If I should be using `wuffs-c genrelease`, how exactly should I be calling it? I haven't been able to figure out how to use it properly.

**Comment by nigeltao** [comment]
Try compiling with -DWUFFS_IMPLEMENTATION or, equivalently, follow the instructions at the top of unsupported-snapshot.h:

```
// Wuffs ships as a "single file C library" or "header file library" as per
// https://github.com/nothings/stb/blob/master/docs/stb_howto.txt
//
// To use that single file as a "foo.c"-like implementation, instead of a
// "foo.h"-like header, #define WUFFS_IMPLEMENTATION before #include'ing or
// compiling it.
```

**Comment by nigeltao** [comment]
Ah, the problem is that you need to define WUFFS_IMPLEMENTATION in all of the files, both `decode.c` and `base.h`, not just the first one. Your revision b7b9ead only defined it in the first one (because `wuffsmain.c` only #include's the first one), and also no longer compiled the second one.

To fix this, either set WUFFS_IMPLEMENTATION via a gcc command line argument instead of by a #define in `wuffsmain.c`, or use `wuffs-c genrelease` to bundle `decode.c` and `base.h` into the one file.

First approach:

```diff
$ git diff
diff --git a/build b/build
index 7efea9b..fd6f5f2 100755
--- a/build
+++ b/build
@@ -3,8 +3,8 @@
 set -e
 export WUFFSROOT=$(go list -e -f {{.Dir}} github.com/google/wuffs)
 
-wuffs-c gen -package_name zstd decode.wuffs consts.wuffs >decode.c
+wuffs-c gen -package_name zstd decode.wuffs consts.wuffs >decode.h
 
-gcc wuffsmain.c -o zstd
+gcc -x c -DWUFFS_IMPLEMENTATION wuffsmain.c $WUFFSROOT/gen/c/base.h -o zstd
 
-rm -f decode.c
+rm -f decode.h
diff --git a/wuffsmain.c b/wuffsmain.c
index 6fb25e9..d11fdb0 100644
--- a/wuffsmain.c
+++ b/wuffsmain.c
@@ -1,9 +1,7 @@
 #include <errno.h>
 #include <unistd.h>
 
-#define WUFFS_IMPLEMENTATION
-
-#include "decode.c"
+#include "decode.h"
 
 #ifndef DST_BUFFER_SIZE
 #define DST_BUFFER_SIZE (16 * 1024)
```

Second approach:

```diff
$ git diff
diff --git a/build b/build
index 7efea9b..a136ca5 100755
--- a/build
+++ b/build
@@ -3,8 +3,10 @@
 set -e
 export WUFFSROOT=$(go list -e -f {{.Dir}} github.com/google/wuffs)
 
-wuffs-c gen -package_name zstd decode.wuffs consts.wuffs >decode.c
+wuffs-c gen -package_name zstd decode.wuffs consts.wuffs >tmp.h
+
+wuffs-c genrelease tmp.h $WUFFSROOT/gen/c/base.h >decode.h
 
 gcc wuffsmain.c -o zstd
 
-rm -f decode.c
+rm -f decode.h tmp.h
diff --git a/wuffsmain.c b/wuffsmain.c
index 6fb25e9..986fb08 100644
--- a/wuffsmain.c
+++ b/wuffsmain.c
@@ -3,7 +3,7 @@
 
 #define WUFFS_IMPLEMENTATION
 
-#include "decode.c"
+#include "decode.h"
 
 #ifndef DST_BUFFER_SIZE
 #define DST_BUFFER_SIZE (16 * 1024)
```

**Comment by mvdan** [comment]
Fixed now - thanks for your help! The final result is different from your suggestions, partially because `gen/c/base.h` is now gone. But the build works, so I'm going to close this for now.

**Comment by nigeltao** [comment]
Yeah, sorry for the bumpy ride. But it's still going to be bumpy in the short term future.

**Comment by mvdan** [comment]
No worries :) as long as the zcat example is maintained, I can just mirror the fixes made there.
